user/add_user/urls.py
from django.urls import path

from .views import add_user, user_detail, users_delete, all_users

app_name = 'user'

urlpatterns = [
    path('add_user/', add_user, name='add_user'),
    path('user_detail/delete/', users_delete, name='users_delete'),
    path('user_detail/all_users/', all_users, name='all_users'),
    path('user_detail/<int:pk>/', user_detail, name='user_detail'),
]

user/user/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('add_user.urls')),
]

user/add_user/models.py
from django.db import models


class User(models.Model):

    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    phone = models.CharField(max_length=25)
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.name
# Create your models here.

user/add_user/views.py
import sqlite3
import requests

from django.shortcuts import render, redirect

from .models import User

def add_user(request):
    last_user = User.objects.all().last()
    slots = ''
    need_button_add_user = True
    if last_user == None:
        need_buttons_delete_and_all_users = False
    else:
        need_buttons_delete_and_all_users = True
    if request.method == "POST":
        if last_user == None:
            number = 1
        else:
            number = last_user.id + 1
        response = requests.get(f'https://jsonplaceholder.typicode.com/users/{number}')
        if response.status_code == 200:
            name = response.json()['name']
            username = response.json()['username']
            phone = response.json()['phone']
            city = response.json()['address']['city']
            User.objects.create(name=name, username=username, phone=phone, city=city)
            need_buttons_delete_and_all_users = True
        if response.status_code == 404:
            slots = 'Больше нет данных для добовления'
            need_button_add_user = False
    context = {
        'slots': slots,
        'need_buttons_delete_and_all_users': need_buttons_delete_and_all_users,
        'need_button_add_user': need_button_add_user
    }
    return render(request, 'add_user.html', context)

def users_delete(request):
    connect = sqlite3.connect('db.sqlite3')
    cursor = connect.cursor()
    cursor.execute('DELETE FROM add_user_user')
    cursor.execute('delete from sqlite_sequence where name="add_user_user"')
    connect.commit()
    cursor.close()
    return redirect('user:add_user')

def all_users(request):
    context = {
        'users': User.objects.all()
    }
    return render(request, 'all_users.html', context)

def user_detail(request, pk):
    user = User.objects.get(id=pk)
    context = {
        'user': user,
    }
    return render(request, 'user_detail.html', context)


user/add_user/templates/add_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add user</title>
</head>
<body>

    <p>{{ slots }}</p>
    {% if need_button_add_user == True %}
    <p><form action="" method="POST">{% csrf_token %}<button>Добавить</button></form></p>
    {% endif %}
    {% if need_buttons_delete_and_all_users == True %}
    <p><form action="{% url 'user:all_users' %}">{% csrf_token %}<button>Все юзеры</button></form></p>
    <p><form action="{% url 'user:users_delete' %}">{% csrf_token %}<button>Удалить</button></form></p>
    {% endif %}

</body>
</html>

user/add_user/templates/all_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for user in users %}
    <p><a href="{% url 'user:user_detail' pk=user.pk %}">{{ user.username }}</a></p>
{% endfor %}
</body>
</html>

user/add_user/templates/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <p>Имя: {{ user.name }}</p>
    <p>Имя пользователя: {{ user.username }}</p>
    <p>Телефон: {{ user.phone }}</p>
    <p>Город: {{ user.city }}</p>


</body>
</html>